name: medimind
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.0.0          # For making API calls
  flutter_dotenv: ^5.0.2  # For environment variables

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/images/logo.png  # Corrected path

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: lib/assets/fonts/SFPRODISPLAYREGULAR.OTF
        - asset: lib/assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: lib/assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: lib/assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: lib/assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
    - family: Lora
      fonts:
        - asset: lib/assets/fonts/Lora-VariableFont_wght.ttf
        - asset: lib/assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
